{
    'name': "SaaS F&B Enterprise",
    'summary': 'Solusi POS, Inventaris, dan Komplain Terintegrasi',
    'description': 'Modul untuk menggantikan sistem lama dengan ekosistem POS, manajemen inventaris, dan manajemen komplain yang terintegrasi.',
    'sequence': -100,
    'author': "Kelompok IF3141",
    'category': 'Sales',
    'version': '1.0',
    'depends': ['base', 'mail'],
    'data': [
        'security/fnb_security.xml',
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/seed_test_data.xml',
        'views/inventory_views.xml',
        'views/order_views.xml',
        'views/menu_views.xml',
        'views/reservation_views.xml',
        'views/payment_views.xml',
        'views/table_views.xml',
        'views/complaint_views.xml',
        'views/feature_access_views.xml',
        'views/menus.xml',
        'data/feature_access_data.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}